-- 004_invites.sql
--
-- Pending invite table.
--
-- Supports the invite flows defined in AC-INV-1 through AC-INV-3 and
-- the IT Executor onboarding path (AC-ONBOARD-3).
--
-- Design notes:
--   - Invites are keyed by email (not user_id) because the invitee may not
--     have a Supabase account yet at invite time.
--   - On acceptance the API looks up the token, creates/links the auth user,
--     inserts the org_members row, and marks accepted_at.
--   - is_it_executor on this table mirrors what will be set on org_members
--     when the invite is accepted.
--   - An org_member cannot be invited twice to the same org (unique constraint
--     on org_id + email, pending only — accepted invites are historical records).
--   - Invites expire after 7 days by default. Expired unaccepted invites are
--     logically invalid; a cleanup job or API check enforces this.
--
-- Apply in Supabase SQL editor after 003_org_settings_and_tracks.sql.

-- =============================================================================
-- 1. Invites table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.invites (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

  org_id          uuid        NOT NULL REFERENCES public.orgs(id) ON DELETE CASCADE,

  -- Who sent the invite (org_admin or manager). API validates that the inviter
  -- is only inviting into their own subtree.
  invited_by      uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Email of the person being invited. Matched against auth.users.email on
  -- acceptance. Not a FK because the user may not exist yet.
  email           text        NOT NULL CHECK (email <> ''),

  -- Role to assign in org_members on acceptance.
  -- org_admin cannot be assigned via invite (AC-INV-2).
  role            text        NOT NULL CHECK (role IN ('manager', 'employee')),

  -- The invited person will report to this user in the org tree.
  -- Must be the inviter's user_id or a user in the inviter's subtree (API validates).
  manager_user_id uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- True if this person is being invited as the IT Executor.
  -- Only one may be set per org at a time (enforced on acceptance by the API,
  -- not at insert time, to allow invite revocation and re-invite).
  is_it_executor  boolean     NOT NULL DEFAULT false,

  -- Secure random token used in the invite URL.
  -- Generated by the API (or here via gen_random_bytes).
  token           text        NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(32), 'hex'),

  -- Timestamps
  created_at      timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz NOT NULL DEFAULT now() + INTERVAL '7 days',
  accepted_at     timestamptz NULL  -- NULL = pending; set on acceptance
);

-- =============================================================================
-- 2. Constraints
-- =============================================================================

-- Prevent duplicate pending invites for the same email + org.
-- Accepted invites (accepted_at IS NOT NULL) are kept as a historical record
-- and excluded from this uniqueness check.
CREATE UNIQUE INDEX IF NOT EXISTS ux_pending_invite_per_email_per_org
  ON public.invites (org_id, lower(email))
  WHERE accepted_at IS NULL;

-- =============================================================================
-- 3. Indexes
-- =============================================================================

-- Token lookup on invite acceptance (hot path).
CREATE INDEX IF NOT EXISTS idx_invites_token
  ON public.invites (token);

-- List pending invites for an org (team settings view).
CREATE INDEX IF NOT EXISTS idx_invites_org_id_pending
  ON public.invites (org_id)
  WHERE accepted_at IS NULL;

-- =============================================================================
-- 4. updated_at trigger (reuse function from 001)
-- =============================================================================

ALTER TABLE public.invites
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DROP TRIGGER IF EXISTS trg_invites_updated_at ON public.invites;
CREATE TRIGGER trg_invites_updated_at
  BEFORE UPDATE ON public.invites
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- NOTES
-- =============================================================================
--
-- Invite acceptance flow (handled in API route):
--   1. Validate token exists, accepted_at IS NULL, expires_at > now().
--   2. Create or find auth.users row for the email.
--   3. Insert org_members row with correct role, manager_user_id, is_it_executor.
--   4. If is_it_executor = true: clear any existing is_it_executor = true on
--      other org_members rows for this org before inserting.
--   5. Set accepted_at = now() on the invite row.
--
-- Invite revocation (org_admin or inviter):
--   Hard delete the invite row. No cascades needed.
